kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-cmd-params-cm
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  # NB! restart argocd services when changing these
  #   kubectl rollout restart -n argocd deployment argocd-server
  #   kubectl rollout restart -n argocd statefulset argocd-application-controller
  #
  ## Controller Properties
  #
  # Set the logging format. One of: text|json (default "text")
  controller.log.format: "json"
  # Set the logging level. One of: debug|info|warn|error (default "info")
  controller.log.level: "info"
  # Sharding algorithm used to balance clusters accross application controller shards (default "legacy")
  controller.sharding.algorithm: legacy
  # Number of allowed concurrent kubectl fork/execs. Any value less than 1 means no limit.
  controller.kubectl.parallelism.limit: "20"
  # Number of application status processors (default 20)
  controller.status.processors: "20"
  # Number of application operation processors (default 10)
  controller.operation.processors: "10"
  #
  ## Server properties
  #
  # Set the logging format. One of: text|json (default "text")
  server.log.format: "json"
  # Set the logging level. One of: debug|info|warn|error (default "info")
  server.log.level: "info"
  # Disable client authentication
  server.disable.auth: "false"
  #
  ## Repo-server properties
  #
  # Set the logging format. One of: text|json (default "text")
  reposerver.log.format: "json"
  # Set the logging level. One of: debug|info|warn|error (default "info")
  reposerver.log.level: "info"
  # Limit on number of concurrent manifests generate requests. Any value less the 1 means no limit.
  reposerver.parallelism.limit: "1"
  # Max combined manifest file size for a single directory-type Application. In-memory manifest representation may be as
  # much as 300x the manifest file size. Limit this to stay within the memory limits of the repo-server while allowing
  # for 300x memory expansion and N Applications running at the same time.
  # (example 10M max * 300 expansion * 10 Apps = 30G max theoretical memory usage).
  reposerver.max.combined.directory.manifests.size: '10M'
  #
  ## ApplicationSet Controller Properties
  #
  # Set the logging format. One of: text|json (default "text")
  applicationsetcontroller.log.format: "json"
  # Set the logging level. One of: debug|info|warn|error (default "info")
  applicationsetcontroller.log.level: "info"
  ## Argo CD Notifications Controller Properties
  # Set the logging format. One of: text|json (default "text")
  notificationscontroller.log.format: "json"
  # Set the logging level. One of: debug|info|warn|error (default "info")
  notificationscontroller.log.level: "info"