apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
spec:
  source:
    path: live
    repoURL: https://github.com/villisco/argocd-apps.git
    targetRevision: HEAD
    directory:
      # apply manifests under subdirectories
      recurse: true