kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-cm
data:
  # PS. disabling "admin.enabled" removes the normal "username+password" login section from landing page if keycloak auth is configured!
  admin.enabled: 'false'
  exec.enabled: 'false'
  exec.shells: bash,sh,powershell,cmd
  statusbadge.enabled: 'true'
  url: https://<ARGOCD_URL>
  users.anonymous.enabled: 'false'
  users.session.duration: 24h
  oidc.config: |
    name: Keycloak
    issuer: https://<KEYCLOAK_URL>/realms/argocd
    logoutURL: https://<KEYCLOAK_URL>/realms/argocd/protocol/openid-connect/logout?client_id=argocd&id_token_hint={{token}}&post_logout_redirect_uri={{logoutRedirectURL}}
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
    # OPTIONAL: add self-signed keycloak SSL cert here
    # otherwise remove the "rootCA:" section
    rootCA: |
      -----BEGIN CERTIFICATE-----
      ...
      ...
      ...
      -----END CERTIFICATE-----